version: "3"
networks:
    ezbids:

services:
    mongodb:
        container_name: brainlife_ezbids-mongodb
        image: mongo:4.4.15
        platform: linux/amd64
        volumes:
            - /data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries:
                5
        networks:
            - ezbids

    api:
        container_name: brainlife_ezbids-api
        build: .
        platform: linux/amd64
        volumes:
            - ./api:/app/api
            - /tmp:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
        working_dir: /app/api
        command:
            ./dev.sh
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
            BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION}
        networks:
            - ezbids

    handler:
        container_name: brainlife_ezbids-handler
        build: ./handler
        platform: linux/amd64
        volumes:
            - .:/app
            - /tmp:/tmp
        depends_on:
            mongodb:
                condition: service_healthy
            api:
                condition: service_healthy
        environment:
            MONGO_CONNECTION_STRING: mongodb://mongodb:27017/ezbids
        networks:
            - ezbids
        tty: true #turn on color for bids-validator output
        command: pm2 start handler.js --attach

    ui:
        container_name: brainlife_ezbids-ui-builder
        env_file:
            - .env
        build: ./ui/Dockerfile-production
        platform: linux/amd64
        volumes:
            - ./ui/dist:/ui/dist
        environment:
            VITE_APIHOST: https://${SERVER_NAME}/api
            VITE_BRAINLIFE_AUTHENTICATION: ${BRAINLIFE_AUTHENTICATION}

    # by default this is not enabled, need to run docker compose with --profile telemetry to enable this service
    telemetry:
        container_name: brainlife_ezbids-telemetry
        build: ./telemetry
        platform: linux/amd64
        depends_on:
            - mongodb
        profiles: ["telemetry"]
        networks:
            - ezbids

    nginx:
        env_file:
            - .env
        container_name: brainlife_ezbids-nginx
        depends_on:
            - ui
            - api
        image: nginx:latest
        platform: linux/amd64
        ports:
            - 80:80
            - 443:443
        networks:
            - ezbids
        volumes:
            - ./nginx/ssl:/etc/nginx/conf.d/ssl/
            - ./nginx/production_nginx.conf:/etc/nginx/conf.d/default.conf
            - ./ui/dist:/usr/share/nginx/html/ezbids:ro